### ISSUE TITLE
I recommend to remove node_modules

### ISSUE THREAD

**Issue by dmc31a42** [telk5093/TELKbot#1]
I recommand to remove node_modules. Basically, node_modules can be downloaded by 'npm install -d'(dependency) if you download module using npm install (module name) --save. If node_modules folder is included, '.git' folder is also placed as much.
node_modules 폴더를 지워주셨으면 합니다. 모듈을 설치 할 때 'npm install (모듈 이름) --save" 로 설치하였으면 node_modules 폴더의 내용물은 'npm install -d'(dependency; 의존성)를 통해 복구할 수 있습니다. node_modules과 같은 폴더가 git에 포함이 되면 '.git'폴더의 용량 또한 그정도 먹게 됩니다.
Recommendation
추천
* 현재 작업물을 stash합니다.(임시 저장합니다. stash를 하는 법을 모르시면 그냥 폴더 통째로 복사해 두셔도 됩니다.)
* Stash your change.(save temporary. If you don't know how to stash, copying folder to other place is also okay
* Reset current branch to parent of 'Add node_modules'(d4ea028)
* (sourcetree기준) 'Add node_modules'의 부모 커밋(이전 커밋)을 오른쪽 클릭하여 '이 커밋까지 현재 브랜치를 초기화를 합니다.'를 수행합니다. 옵션은 soft(현재 작업물을 유지합니다.), hard(현재 작업물을 버립니다. 그 커밋 이후로 모든 작업물이 버려집니다), mixed(soft와 hard를 적절히). 이 단계에서 작업물이 엉클어질 수 있기에 폴더를 백업해두시기 바랍니다.
* Then, push your change, of course, it should show error, run terminal to type command. type 'git push -f'(-f means force). It should pushed.
* 그리고 이 단계에서 푸시를 합니다. 이 단계에서 오류가 나는 것은 당연합니다. 터미널 창을 띄워서 명령어 기반으로 git을 쓸 수 있게 준비합니다.(sourcetree에서는 오른쪽 상단에 Terminal 버튼이 있습니다). 'git push -f'(-f는 강제로 수행하게 하는 옵션입니다.)를 입력 후 엔터를 누릅니다. 그러면 정상적으로 push되는 것을 볼 수 있습니다.
* If you select hard, apply stash as you backuped. If you select soft or mixed, maybe all your work still stay. check.
* 하드를 선택했으면 그전에 백업해둔 스태시를 적용합니다.(왼쪽 스태시에 지정해둔 이름으로 존재, 오른쪽 클릭 및 적용) 소프트나 믹스를 선택했다면 작업물이 남아있겠지만 확인해보아야함. 만약 작업물에 손상이 가해졌으면 백업해둔 폴더를 (.git폴더 제외) 덮어씌워서 해결할 수 있습니다.
* add 'node_modules' folder to .gitignore
* 'node_modules' 폴더를 .gitignore파일에 등록해둡니다.(.gitignore 파일은 regexp을 기반으로 한 무시 목록 파일입니다. 작성법을 모르겠으면 https://www.gitignore.io/api/node 을 다운받아서 .gitignore 이름으로 저장하여 프로젝트 폴더 최상단에 둡니다) 이 .gitignore 파일을 staging(스테이징)하면 node_modules 폴더가 unstaged 목록에서 사라집니다.
* make sure you notice to use 'npm install -d'
* 'npm install -d'를 통해 의존성 파일을 다운받을 것을 README 등을 통하여 알립니다.

**Comment by dmc31a42** [comment]
만약 'Add node_modules'(d4ea028) 커밋 이후로 커밋이 더 있다면 그냥 '.gitignore'을 staging하고 node_modules 폴더를 지우시고난 뒤 지운 파일들의 정보를 staging하시면 됩니다. 위의 절차는 그냥 그런 파일을 올렸단 흔적 자체를 없엘뿐.

**Comment by telk5093** [comment]
하... 한글로 적어주셔도 돼요....;;;
